export const ENGLISH_WEBVIEW_STRINGS = {
  documentTitle: 'Agent Terminal Panel',
  sessionSidebarAria: 'Agent session list',
  sessionHeading: 'Sessions',
  newDefaultSession: 'Create session with default command',
  otherLaunchMethods: 'Choose another launch method',
  sessionListAria: 'Agent sessions',
  sessionSplitterAria: 'Resize session list',
  findTerminal: 'Find in current terminal',
  pickAttachmentsTitle: 'Choose image files; hold Shift when dragging from VS Code Explorer',
  pickAttachmentsAria: 'Choose image files',
  renameCurrentSession: 'Rename current session',
  rerunCurrentSession: 'Rerun launch command',
  rerunDefaultSession: 'Rerun the current default launch command',
  rerunProfileSession: 'Rerun this saved launch command',
  rerunCustomSession: 'Rerun this one-time custom command',
  rerunResumeSession: 'Run the Provider Resume command again',
  restoreAll: 'Restore all',
  dismiss: 'Dismiss',
  searchInputAria: 'Find in current terminal',
  searchPreviousTitle: 'Previous match (Shift+Enter)',
  searchPreviousAria: 'Previous match',
  searchNextTitle: 'Next match (Enter)',
  searchNextAria: 'Next match',
  searchCloseTitle: 'Close find (Escape)',
  searchCloseAria: 'Close find',
  dropImages: 'Drop images',
  dropImagesHint: 'Hold Shift when dragging from VS Code Explorer or a system file manager, or use the image button in the header.',
  emptyState: 'No Agent sessions yet',
  emptyNewDefault: 'Create with default command',
  emptyOtherLaunch: 'Choose another launch method',
  launchMenuAria: 'Agent session launch methods',
  doubleClickRename: 'Double-click to rename',
  restartForkUnavailable: 'A Fork launch runs once. Resume the new session from history instead.',
  workspaceRestoreTitle: 'The previous window kept {0} sessions',
  workspaceRestoreMore: ' and {0} total',
  workspaceRestoreHint: 'Restore after your Agent or network environment is ready',
  statusRunning: 'Running',
  statusWaiting: 'Waiting for input',
  statusApproval: 'Waiting for approval',
  statusCompleted: 'Completed',
  statusExited: 'Exited ({0})',
  unreadStatus: 'Unread status',
  closeSession: 'Close session',
  closeNamedSession: 'Close {0}',
  sessionName: 'Session name',
  launchProfiles: 'Launch commands',
  noLaunchProfiles: 'No additional launch commands configured',
  chooseWorkingDirectory: 'Choose working directory',
  useDefaultLaunchCommand: 'Use the default launch command',
  oneTimeCustomCommand: 'One-time custom command',
  customCommandDescription: 'Does not change the default or saved launch commands',
  providerHistory: 'Provider session history',
  providerHistoryDescription: 'Resume / Fork sessions in the current workspace',
  reopenNamedSession: 'Reopen “{0}”',
  reopenClosedSession: 'Reopen recently closed session',
  shortClosedRecords: '{0} short-term closed-session records are available',
  recreateClosedSession: 'Recreate with the original name, cwd, and launch command',
  restoreWindowSessions: 'Restore {0} sessions from the previous window',
  restoreWindowSessionsDescription: 'Manually restore retained default sessions',
  manageLaunchProfiles: 'Manage launch commands',
  openPanelSettings: 'Open Agent Terminal Panel settings',
  noSearchResults: 'No results',
  searchResultCount: '{0} results',
  noActiveTerminal: 'No active terminal',
  selectSessionFirst: 'Create or select a terminal session first',
  attachmentInserted: 'Inserted paths for {0} images',
  attachmentPartiallyInserted: 'Inserted {0}; {1} failed',
  noSupportedImages: 'No supported images to insert',
  unreadableDrop: 'No readable images were received; use copy and paste for VS Code Explorer items if needed',
  attachmentLimit: 'Process up to {0} images at once',
  imageFallbackName: 'image',
  imageTooLarge: '{0}: larger than 25 MB',
  imageBatchTooLarge: '{0}: total image size exceeds 50 MB',
  savingImages: 'Saving images on the workspace host…',
  imageReadFailed: '{0}: could not be read',
  creatingTerminal: 'Creating terminal',
  startingWorkspaceProcess: 'Starting process on the workspace host · {0}',
  communicationQuiet: 'Communication quiet for {0}',
  communicationStalled: 'Potentially stalled for {0}',
  communicationIdle: 'Communication idle',
  communicationIdleCompact: 'Idle',
  communicationUnavailable: 'Monitoring pending',
  communicationUnavailableCompact: 'Pending',
  communicationActive: 'Communication active',
  communicationActiveCompact: 'Active',
  waitingFirstResponse: 'Waiting for first response {0}',
  connectionCountOne: '{0} connection',
  connectionCount: '{0} connections',
  firstResponse: 'First response {0}…',
  firstEvent: 'First event {0}*',
  healthStatus: 'Health: {0}',
  healthBasis: 'Basis: {0}',
  ptyRates: 'PTY: ↓ {0} · ↑ {1}',
  probeUnavailable: 'probe currently unavailable',
  processBytesUnavailable: 'per-process byte counters unavailable on this platform',
  agentUsesLoopback: 'The Agent connection targets a local loopback proxy.',
  proxyUpstream: '{0} upstream (shared-process estimate): ↓ {1} · ↑ {2}',
  networkProbeError: 'Network probe unavailable: {0}',
  codexTtft: 'Codex TTFT: {0} (exact JSONL task_complete value)',
  turnOutputTokens: 'Current/recent turn output tokens: {0}',
  codexTotalTokens: 'Codex session total tokens: {0}',
  firstEventDisclaimer: '“First event” is the first JSONL model event and is not exact TTFT.',
  basisNetwork: 'Agent process TCP socket',
  basisProvider: 'Provider is running a local tool',
  basisPty: 'PTY output activity (not network traffic)',
  basisUnavailable: 'No source available',
  windowsTcpConnections: 'Windows TCP connections'
} as const;

export type WebviewStringKey = keyof typeof ENGLISH_WEBVIEW_STRINGS;
export type WebviewStrings = Record<WebviewStringKey, string>;

export const CHINESE_WEBVIEW_STRINGS: WebviewStrings = {
  documentTitle: 'Agent Terminal Panel',
  sessionSidebarAria: 'Agent 会话列表',
  sessionHeading: '会话',
  newDefaultSession: '使用默认命令新建会话',
  otherLaunchMethods: '选择其他启动方式',
  sessionListAria: 'Agent 会话',
  sessionSplitterAria: '调整会话列表宽度',
  findTerminal: '在当前终端中查找',
  pickAttachmentsTitle: '选择图片文件；从 VS Code 资源管理器拖入时请按住 Shift',
  pickAttachmentsAria: '选择图片文件',
  renameCurrentSession: '重命名当前会话',
  rerunCurrentSession: '重新运行启动命令',
  rerunDefaultSession: '重新运行当前默认启动命令',
  rerunProfileSession: '重新运行此保存的启动命令',
  rerunCustomSession: '重新运行此一次性自定义命令',
  rerunResumeSession: '再次运行 Provider Resume 命令',
  restoreAll: '恢复全部',
  dismiss: '忽略',
  searchInputAria: '在当前终端中查找',
  searchPreviousTitle: '上一个匹配项 (Shift+Enter)',
  searchPreviousAria: '上一个匹配项',
  searchNextTitle: '下一个匹配项 (Enter)',
  searchNextAria: '下一个匹配项',
  searchCloseTitle: '关闭查找 (Escape)',
  searchCloseAria: '关闭查找',
  dropImages: '放下图片',
  dropImagesHint: 'VS Code 资源管理器或系统文件管理器拖入时请按住 Shift；也可点击顶栏图片按钮',
  emptyState: '还没有 Agent 会话',
  emptyNewDefault: '使用默认命令新建',
  emptyOtherLaunch: '选择其他启动方式',
  launchMenuAria: 'Agent 会话启动方式',
  doubleClickRename: '双击重命名会话',
  restartForkUnavailable: 'Fork 启动只执行一次；请从历史记录 Resume 新会话',
  workspaceRestoreTitle: '上次窗口保留了 {0} 个会话',
  workspaceRestoreMore: ' 等 {0} 个',
  workspaceRestoreHint: '准备好代理或网络环境后再恢复',
  statusRunning: '运行中',
  statusWaiting: '等待输入',
  statusApproval: '等待审批',
  statusCompleted: '已完成',
  statusExited: '已结束（{0}）',
  unreadStatus: '有未读状态',
  closeSession: '关闭会话',
  closeNamedSession: '关闭 {0}',
  sessionName: '会话名称',
  launchProfiles: '启动命令',
  noLaunchProfiles: '尚未配置其他启动命令',
  chooseWorkingDirectory: '选择工作目录',
  useDefaultLaunchCommand: '使用默认启动命令',
  oneTimeCustomCommand: '一次性自定义命令',
  customCommandDescription: '不修改默认命令或已保存启动命令',
  providerHistory: 'Provider 历史会话',
  providerHistoryDescription: '当前 workspace 的 Resume / Fork',
  reopenNamedSession: '重新打开“{0}”',
  reopenClosedSession: '重新打开最近关闭的会话',
  shortClosedRecords: '保留了 {0} 个短期关闭记录',
  recreateClosedSession: '使用原名称、cwd 和启动命令重新创建',
  restoreWindowSessions: '恢复上次窗口的 {0} 个会话',
  restoreWindowSessionsDescription: '手动恢复仍保留的默认会话',
  manageLaunchProfiles: '管理启动命令',
  openPanelSettings: '打开 Agent Terminal Panel 设置',
  noSearchResults: '无结果',
  searchResultCount: '{0} 个结果',
  noActiveTerminal: '没有活动终端',
  selectSessionFirst: '请先创建或选择一个终端会话',
  attachmentInserted: '已插入 {0} 张图片的路径',
  attachmentPartiallyInserted: '已插入 {0} 张，{1} 张失败',
  noSupportedImages: '没有可插入的图片',
  unreadableDrop: '未收到可读取的图片；从 VS Code 资源管理器拖入时可改用复制粘贴',
  attachmentLimit: '一次最多处理 {0} 张图片',
  imageFallbackName: '图片',
  imageTooLarge: '{0}：超过 25 MB',
  imageBatchTooLarge: '{0}：本次图片总量超过 50 MB',
  savingImages: '正在保存图片到 workspace host…',
  imageReadFailed: '{0}：读取失败',
  creatingTerminal: '正在创建终端',
  startingWorkspaceProcess: '正在 workspace host 启动进程 · {0}',
  communicationQuiet: '通信静默 {0}',
  communicationStalled: '疑似停滞 {0}',
  communicationIdle: '通信空闲',
  communicationIdleCompact: '空闲',
  communicationUnavailable: '监测待就绪',
  communicationUnavailableCompact: '待就绪',
  communicationActive: '通信活跃',
  communicationActiveCompact: '活跃',
  waitingFirstResponse: '等待首响应 {0}',
  connectionCountOne: '{0} 个连接',
  connectionCount: '{0} 个连接',
  firstResponse: '首响应 {0}…',
  firstEvent: '首事件 {0}*',
  healthStatus: '健康状态：{0}',
  healthBasis: '判断依据：{0}',
  ptyRates: 'PTY：↓ {0} · ↑ {1}',
  probeUnavailable: '探针当前不可用',
  processBytesUnavailable: '当前平台不提供逐进程字节',
  agentUsesLoopback: 'Agent 连接目标是本地 loopback 代理。',
  proxyUpstream: '{0} 上游（进程共享估计）：↓ {1} · ↑ {2}',
  networkProbeError: '网络探针不可用：{0}',
  codexTtft: 'Codex TTFT：{0}（JSONL task_complete 精确值）',
  turnOutputTokens: '当前/最近回合输出 tokens：{0}',
  codexTotalTokens: 'Codex 会话累计 tokens：{0}',
  firstEventDisclaimer: '“首事件”来自 JSONL 首个模型事件，不等同于精确 TTFT。',
  basisNetwork: 'Agent 进程 TCP socket',
  basisProvider: 'Provider 正在执行本地工具',
  basisPty: 'PTY 输出活动（非网络流量）',
  basisUnavailable: '暂无可用来源',
  windowsTcpConnections: 'Windows TCP 连接'
};

export function getWebviewStrings(language: string): WebviewStrings {
  return language.toLowerCase().replace('_', '-').startsWith('zh-cn')
    ? CHINESE_WEBVIEW_STRINGS
    : ENGLISH_WEBVIEW_STRINGS;
}

export function formatWebviewString(template: string, ...values: Array<string | number>): string {
  return template.replace(/\{(\d+)\}/gu, (match, index: string) => {
    const value = values[Number(index)];
    return value === undefined ? match : String(value);
  });
}
